#!/bin/sh

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

echo  "deb [arch=amd64] https://download.docker.com/linux/debian RELEASE stable" > /etc/apt/sources.list.d/docker.list

apt-get update
apt-get -y install docker-ce docker-ce-cli containerd.io

systemctl enable docker

# docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose